
const fakeData = [
  {
    id: "1",
    title: "Software Engineer",
    company_name: "Example Corp",
    location_city: "San Francisco",
    work_location: "Remote",
    employment_type: "Full-time",
    skills: [
      { skill_id: "1", skill_name: "JavaScript" },
      { skill_id: "2", skill_name: "React" },
      { skill_id: "3", skill_name: "Node.js" },
    ],
    soft_skills: ["Teamwork", "Problem Solving"],
    matchScore: 75,
    isSaved: false,
    associations: ["Association 1", "Association 2"],
    company_id: "1",
  },
  {
    id: "2",
    title: "Data Analyst",
    company_name: "Data Co.",
    location_city: "New York",
    work_location: "Office",
    employment_type: "Part-time",
    skills: [
      { skill_id: "4", skill_name: "Data Analysis" },
      { skill_id: "5", skill_name: "SQL" },
      { skill_id: "6", skill_name: "Excel" },
    ],
    soft_skills: ["Communication", "Critical Thinking"],
    matchScore: 90,
    isSaved: true,
    associations: ["Association 3"],
    company_id: "2",
  },
  {
    id: "3",
    title: "Frontend Developer pro",
    company_name: "Web Dev Inc.",
    location_city: "Los Angeles",
    work_location: "Office",
    employment_type: "Full-time",
    skills: [
      { skill_id: "7", skill_name: "HTML" },
      { skill_id: "8", skill_name: "CSS" },
      { skill_id: "9", skill_name: "React" },
    ],
    soft_skills: ["Creativity", "Attention to Detail"],
    matchScore: 85,
    isSaved: true,
    associations: ["Association 4"],
    company_id: "3",
  },
  {
    id: "4",
    title: "Marketing Manager",
    company_name: "Exaketing Pro",
    location_city: "Chicago",
    work_location: "Remote",
    employment_type: "Full-time",
    skills: [
      { skill_id: "10", skill_name: "Marketing Strategy" },
      { skill_id: "11", skill_name: "SEO" },
      { skill_id: "12", skill_name: "Social Media" },
    ],
    soft_skills: ["Leadership", "Analytical Thinking"],
    matchScore: 78,
    isSaved: false,
    associations: ["Association 5", "Association 6"],
    company_id: "4",
  },
  {
    id: "5",
    title: "Graphic Designer",
    company_name: "Design Solutions",
    location_city: "Miami",
    work_location: "Office",
    employment_type: "Part-time",
    skills: [
      { skill_id: "13", skill_name: "Adobe Photoshop" },
      { skill_id: "14", skill_name: "Illustrator" },
      { skill_id: "15", skill_name: "Graphic Design" },
    ],
    soft_skills: ["Creativity", "Attention to Detail"],
    matchScore: 92,
    isSaved: true,
    associations: ["Association 7"],
    company_id: "5",
  },
  {
    id: "6",
    title: "Accountant",
    company_name: "Finance Group",
    location_city: "Houston",
    work_location: "Remote",
    employment_type: "Full-time",
    skills: [
      { skill_id: "16", skill_name: "Accounting" },
      { skill_id: "17", skill_name: "Financial Analysis" },
      { skill_id: "18", skill_name: "Excel" },
    ],
    soft_skills: ["Analytical Thinking", "Attention to Detail"],
    matchScore: 82,
    isSaved: false,
    associations: ["Association 8", "Association 9"],
    company_id: "6",
  },
];

export default fakeData;
